savane/tracker/urls.py
# Trackers URLs
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from django.utils.translation import ugettext, ugettext_lazy as _
from django.views.generic.list_detail import object_detail, object_list
from django.views.generic.create_update import create_object, update_object
from django.contrib.auth.decorators import login_required
from savane.utils import get_site_name
from savane.perms import only_project_admin
from savane.django_utils import decorated_patterns
import views
import models as tracker_models

urlpatterns = patterns ('',)

urlpatterns += patterns ('',
  url(r'^(?P<tracker>[-\w]+)/$', views.item_list,
      { 'paginate_by': 50,
        'extra_context' : { 'title' : _("Bugs") }, },
      name='item_list'),
  url(r'^(?P<tracker>[-\w]+)/(?P<object_id>\d+)/$', views.item_detail,
      {},
      name='item_detail'),
)

savane/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',)

urlpatterns += patterns('',
  # Home/presentation pages
  (r'', include('savane.svmain.urls', namespace='svmain')),
  # User account
  (r'^my/', include('savane.my.urls', namespace='my')),
  (r'^news/', include('savane.svnews.urls', namespace='svnews')),
  (r'^people/', include('savane.svpeople.urls', namespace='svpeople')),
  (r'^tracker/', include('savane.tracker.urls', namespace='tracker')),
)

urls.py
# URL dispatching
# Copyright (C) 2009, 2010  Sylvain Beucler
# Copyright (C) 2009  Jonathan Gonzalez V.
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',)

# Savane
urlpatterns += patterns('',
  (r'', include('savane.urls', namespace='savane')),
)

# Generic login/logout/change_pass/etc.
urlpatterns += patterns('',
  (r'^accounts/logout/$', 'django.contrib.auth.views.logout',
    {'next_page' : '/'}),  # redirect to '/' instead of login page
  # django-registration
  (r'^accounts/', include('registration.backends.default.urls')),
  (r'^accounts/', include('django.contrib.auth.urls')),
)

# Browse the false mailbox, for demo websites:
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^dev/webmail/', include('webmail_locmem.urls')),
    )

# Enable the auto-admin:
from django.contrib import admin
import django
admin.autodiscover()

urlpatterns += patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^dev/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^dev/', include(admin.site.urls)),
)
# TODO: implement a lighter admin interface for non-dev admins (to
# manage project configurations, skills categories, etc.)
# It could reside at '^siteadmin/'.

# Static content
if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^' + settings.STATIC_MEDIA_URL[1:] + '(?P<path>.*)$', 'serve',
         {'document_root' : settings.STATIC_MEDIA_ROOT, 'show_indexes' : True}),
    )

savane/svnews/models.py
# News and comments structure
# Copyright (C) 2004, 2005  Mathieu Roy
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
import django.contrib.auth.models as auth_models
from savane.utils import markup
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _, ungettext

# - news_byte
class ApprovedNewsManager(models.Manager):
    def get_query_set(self):
        return super(self.__class__, self).get_query_set().filter(is_approved__in=(0,1,2))
class News(models.Model):
    """
    One piece of news
    """
    class Meta:
        ordering = ('-date',)

    IS_APPROVED_CHOICES = (
        ('0', 'approved for project page'),
        ('1', 'approved for site frontpage news'),
        ('2', 'refused for site frontpage news'),
        ('4', 'removed'),
        ('5', 'proposed'),
        )
    group = models.ForeignKey(auth_models.Group)
    submitted_by = models.ForeignKey(auth_models.User)
    is_approved = models.CharField(max_length=1, choices=IS_APPROVED_CHOICES, db_index=True)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    date_last_edit = models.DateTimeField(auto_now=True, db_index=True)
    summary = models.CharField(max_length=255)
    details = models.TextField()
    # Savane3's 'forum_id', the most visible id, is now 'id'.
    # Savane3's 'id', only used in administration screens, is dropped.

    objects = models.Manager() # default manager
    approved_objects = ApprovedNewsManager()

    def get_details_short(self):
        # if the news item is large (>500 characters),
        # only show about 250 characters of the story
        story = self.details
        strlen_story = len(story);
        if strlen_story > 500:
            # if there is a linebreak close to the 250 character
            # mark, we use it to truncate the news item, so that
            # the markup will not be confused.
            # We accept the range from 240 to 350 characters, else
            # the news item will be split on whitespace.
            # See bug #7634
            linebreak = self.details.find("\n", min(strlen_story, 240))
            if linebreak >= 0 and linebreak < 350:
                truncate = linebreak
            else:
                truncate = story[:250].rfind(' ')
                if truncate == False:
                    truncate = 250
            summ_txt = story[:truncate]
            summ_txt += " ..."
            summ_txt = markup.full(summ_txt)
            summ_txt += '<br />'
            summ_txt += '<a href="%s">' % reverse('savane:svnews:news_detail', args=[self.pk])
            summ_txt += _("[Read more]")
            summ_txt += '</a>'
        else:
            # this is a short news item. just display it.
            summ_txt = markup.full(story)
        return summ_txt

class Comment(models.Model):
    """
    A comment on the news item
    """
    news = models.ForeignKey(News)  # savane_old: uses forum_id through forum_group_list
    posted_by = models.ForeignKey(auth_models.User, related_name='svnews_comment_set')
    subject = models.CharField(max_length=255)
    body = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    is_followup_to = models.ForeignKey("Comment")
    thread = models.ForeignKey("Thread")
    #has_followups = models.BooleanField()

class Notification(models.Model):
    """
    Notify this User when comments are posted to this item
    """
    news = models.ForeignKey(News)  # savane_old: uses forum_id through forum_group_list
    user = models.ForeignKey(auth_models.User)

class LastVisit(models.Model):
    """
    Mark the last visit date from a user, so that comments posted
    since then are highlighted
    """
    news = models.ForeignKey(News)  # savane_old: uses forum_id through forum_group_list
    user = models.ForeignKey(auth_models.User)
    date = models.DateTimeField(auto_now=True)

class Thread(models.Model):
    """
    Counter for top-level discussions ("threads")

    Threads are currently used to get all messages in a thread without
    using expensive recursive querying.

    TODO: there are better SQL solutions based on tree structures
    """
    pass

savane/tracker/views.py
# Trackers
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
#
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _, ungettext
import django.contrib.auth.models as auth_models
from django.views.generic.list_detail import object_detail, object_list
import savane.tracker.models as tracker_models
from annoying.decorators import render_to
from savane.middleware.exception import HttpAppException

def item_list(request, tracker, extra_context={}, paginate_by=None):
    queryset = tracker_models.Item.objects.filter(tracker=tracker).order_by('-public_%s' % tracker)
    return object_list(request, queryset=queryset, extra_context=extra_context,
                       paginate_by=paginate_by)

@render_to('tracker/item_form.html', mimetype=None)
def item_detail(request, tracker, object_id, extra_context={}):
    tracker = get_object_or_404(tracker_models.Tracker, name=tracker)

    kwargs = {tracker.get_public_id_item_field() : object_id}
    item = get_object_or_404(tracker_models.Item, **kwargs)

    if item.privacy == 0:  # reverse meaning...
        # Allowed: members with 'private items' privs
        if not request.user.is_superuser:
            raise HttpAppException(_("Access denied") + _(": ") + _("private item"))

    context = {
        'object' : item,
        }
    context.update(extra_context)
    return context

templates/tracker/item_form.html
{% extends "base.html" %}
{% load i18n %}
{% load svmarkup %}

{% block title %}
{{object.group.name}} - {{object.get_tracker_name}}{% trans ": " %}
  {{object.get_shortcut}},
  {{object.get_summary|truncatewords:5}}
{% endblock %}

{% block icon %}{{object.get_icon_name}}{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{{STATIC_MEDIA_URL}}savane/css/tracker.css" />
{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}

<h1 class="{{object.get_priority_css_class}}">
  <em><a href="{% url savane:tracker:item_detail object.tracker_id object.get_public_id %}"
    >{{object.get_shortcut}}</a></em>{% trans ": " %}
  {{object.get_summary}}
</h1>

<table class="tracker_item">
<tr>
  <th>{% trans "Submitted by" %}{% trans ": " %}</th>
  <td>
    {% if object.submitted_by_id %}
      {% if object.submitted_by %}
      <a href="{% url savane:svmain:user_detail object.submitted_by.username %}"
      >{{object.submitted_by.get_full_name}}
        &lt;{{object.submitted_by.username}}&gt;</a>
      {% else %}
        <strong>{% trans "Invalid user ID" %}</strong>
      {% endif %}
    {% else %}
    {% trans "Anonymous" %}
    {% endif %}
  </td>
  <td colspan="2" class="button">
    <input type="submit" style="font-weight: bold;" value="{% trans "Submit changes and browse items" %}" />
  </td>
</tr>
<tr>
  <th>{% trans "Submitted on" %}{% trans ": " %}</th>
  <td width="35%">{{ object.date }}</td>
  <td colspan="2" class="button"><input type="submit" value="{% trans "Submit changes and return to this item" %}" /></td>
</tr>
<tr><td colspan="4" style="height: 15px;"></td></tr>
{{object.get_form}}
<tr>
  <th>{% trans "Summary" %}{% trans ": "%}</th>
  <td colspan="3">
    <input type="text" name="summary" value="{{object.get_summary}}"
      maxlength="{{object.get_field_defs.summary.input_maxlength}}"
      size="{{object.get_field_defs.summary.input_size}}"
    />
  </td>
</tr>
</table>


<h2>{% trans "Post a comment" %}</h2>

<p class="preinput">{% trans "Add a new comment" %}{% trans ": " %}<br />
  <textarea cols="65" rows="16" name="comment"></textarea>
</p>
<p class="preinput">{% filter force_escape %}{% trans "Comment type & canned response" %}{% endfilter %}{% trans ": " %}<br />
  <select name="comment_type_id">
    {% for choice in object.get_field_defs.comment_type_id.choices %}
    <option value="{{choice.value_id}}">{{choice.value}}</option>
    {% endfor %}
  </select>
  &nbsp;
  {% if 0 %}
  <select named="canned_response">
  <option value="">TODO</option>
  </select>
  {% else %}
  {% trans "No canned response available" %}
  &nbsp;
  <a class="smaller" href="TODO">
  ({% trans "Or define a new canned response" %})
  </a>
  {% endif %}
</p>

<h2>{% trans "Discussion" %}</h2>

<table class="comments">
{% for comment in object.comment_set.all reversed %}
<tr class="{% cycle 'boxitem' 'boxitemalt' as rowcolor %}">
  <td>
    <a name="comment{{forloop.counter}}" href="#comment{{forloop.count}}"
      class="preinput">
      {{comment.date}},
      {% blocktrans with forloop.counter as number %}comment #{{number}}{% endblocktrans %}{% trans ": " %}
    </a><br />
    {{ comment.message|svmarkup_rich }}
  </td>
  <td class="boxitemextra">
    {% if comment.posted_by_id %}
      {% if comment.posted_by %}
      <a href="{% url savane:svmain:user_detail comment.posted_by.username %}"
      >{{comment.posted_by.get_full_name}}
        &lt;{{comment.posted_by.username}}&gt;</a>
      {% else %}
        <strong>{% trans "Invalid user ID" %}</strong>
      {% endif %}
    {% else %}
    {% trans "Anonymous" %}
    {% endif %}
    <!-- TODO: display poster privs -->
  </td>
</tr>
{% endfor %}
<tr class="{% cycle rowcolor %}">
  <td>
    <a name="comment0" href="#comment0"
      class="preinput">
      {{object.date}}, <strong>{% trans "original submission" %}{% trans ": " %}</strong>
    </a><br />
    {{ object.details|svmarkup_full }}
  </td>
  <td class="boxitemextra">
    {% if object.submitted_by_id %}
      {% if object.submitted_by %}
      <a href="{% url savane:svmain:user_detail object.submitted_by.username %}"
      >{{object.submitted_by.get_full_name}}
        &lt;{{object.submitted_by.username}}&gt;</a>
      {% else %}
        <strong>{% trans "Invalid user ID" %}</strong>
      {% endif %}
    {% else %}
    {% trans "Anonymous" %}
    {% endif %}
    <!-- TODO: display poster privs -->
  </td>
</tr>
</table>

<h2>{% trans "Attached files" %}</h2>

<h2>{% trans "Dependencies" %}</h2>

<h2>{% trans "Mail notification carbon-copy list" %}</h2>

<h2>{% trans "Votes" %}</h2>

<input type="submit" value="{% trans "Submit changes" %}" />
</form>

<h2>{% trans "History" %}</h2>

<p>
{% blocktrans count object.itemhistory_set.count as count %}Follows {{count}} latest change.{% plural %}Follow {{count}} latest changes.{% endblocktrans %}
</p>

<table class="history smaller box">
<tr>
  <th>Date</th>
  <th>Changed by</th>
  <th>Updated field</th>
  <th>Previous value</th>
  <th width="1">=&gt;</th>
  <th>Replaced By</th>
</tr>
{% for history in object.itemhistory_set.all %}
{% ifchanged history.date history.mod_by %}
<tr class="{% cycle 'boxitem' 'boxitemalt' as rowcolor %}">
  <td>{{history.date}}</td>
  <td>
    {% if history.mod_by_id %}
      {% if history.mod_by %}
      <a href="{% url savane:svmain:user_detail history.mod_by.username %}"
      >{{history.mod_by.username}}</a>
      {% else %}
        <strong>{% trans "Invalid user ID" %}</strong>
      {% endif %}
    {% else %}
    {% trans "Anonymous" %}
    {% endif %}
  </td>
{% else %}
<!-- skip {% cycle rowcolor %} once -->
<tr class="{% cycle rowcolor %}">
  <td></td><td></td>
{% endifchanged %}
  <td>{{history.field}}</td><!-- TODO: field definition['label'] -->
  <td class="old_value">{{history.old_value}}</td><!-- TODO: if SB, use FieldChoice -->
  <td><img width="24" src="{{STATIC_MEDIA_URL}}savane/images/common/arrows1/next.orig.png" border="0" alt="=&gt;" /></td>
  <td>{{history.new_value}}</td>
</tr>
{% endfor %}
</table>

{% endblock %}
{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/tracker/item_list.html
{% extends "base.html" %}
{% load i18n %}

{% block icon %}bug{% endblock %}

{% block content %}

{% include "svmain/pagination.inc.html" %}

<form action="." method="get">
  {% trans "Search" %}: <input type="text" name="q" value="TODO {{q}}" />
</form>

{% if object_list %}
  <table class="box">
    <tr><th>{% trans "Id" %}</th><th>{% trans "Summary" %}</th></tr>
    {% for object in object_list %}
    <tr class="{% cycle 'boxitem' 'boxitemalt' %}">
      <td><a href="{{ object.get_absolute_url }}">{{ object.get_public_id }}</a></td>
      <td><a href="{{ object.get_absolute_url }}">{{ object.get_summary }}</a></td>
    </tr>
    {% endfor %}
  </table>
{% else %}
    <p>{% trans "No items." %}</p>
{% endif %}

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}