savane/svpeople/urls.py
# Jobs URLs
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
import views
from django.utils.translation import ugettext, ugettext_lazy as _
from django.views.generic.list_detail import object_detail
from django.views.generic.create_update import create_object, update_object
from django.contrib.auth.decorators import login_required
from savane.utils import get_site_name
import models as svpeople_models
import forms as svpeople_forms
from savane.perms import only_project_admin
from savane.django_utils import decorated_patterns

urlpatterns = patterns ('',)

urlpatterns += patterns ('',
  url(r'^$', views.index,
      { 'extra_context' : { 'title' : _("Projects needing help"), }, },
      name='index'),
  url(r'^category/(?P<category_id>\d+)/$', views.job_list_by_category,
      {},
      name='job_list_by_category'),
  url(r'^type/(?P<type_id>\d+)/$', views.job_list_by_type,
      { 'extra_context' : { 'title' : _("Project help wanted"), }, },
      name='job_list_by_type'),
  url(r'^group/(?P<slug>[-\w]+)/$', views.job_list_by_group,
      { 'extra_context' : { 'title' : _("Looking for a job to edit"), }, },
      name='job_list_by_group'),
  url(r'^job/(?P<object_id>\d+)/$', object_detail,
      { 'queryset' : svpeople_models.Job.objects.all(),
        'extra_context' : { 'title' : _("View a job"), }, },
      name='job_detail'),
  # access restriction done in job_update():
  url(r'^job/(?P<object_id>\d+)/edit/$', views.job_update,
      { 'extra_context' : { 'title' : _("Edit a job for your project"),
                            'action' : _("Update") }, },
      name='job_edit'),
)
urlpatterns += decorated_patterns ('', only_project_admin,
  url(r'^group/(?P<slug>[-\w]+)/add/$', views.job_add,
      { 'extra_context' : { 'title' : _("Create a job for your project"),
                            'add' : True,
                            'action' : _("Continue >>") }, },
      name='job_add'),
)
urlpatterns += decorated_patterns ('', login_required,
  url(r'^my_info/$', views.userinfo_update,
      { 'extra_context' : { 'title' : _("Edit your resume & skills"), }, },
      name='userinfo_update'),
)

savane/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',)

urlpatterns += patterns('',
  # Home/presentation pages
  (r'', include('savane.svmain.urls', namespace='svmain')),
  # User account
  (r'^my/', include('savane.my.urls', namespace='my')),
  (r'^news/', include('savane.svnews.urls', namespace='svnews')),
  (r'^people/', include('savane.svpeople.urls', namespace='svpeople')),
  (r'^tracker/', include('savane.tracker.urls', namespace='tracker')),
)

urls.py
# URL dispatching
# Copyright (C) 2009, 2010  Sylvain Beucler
# Copyright (C) 2009  Jonathan Gonzalez V.
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',)

# Savane
urlpatterns += patterns('',
  (r'', include('savane.urls', namespace='savane')),
)

# Generic login/logout/change_pass/etc.
urlpatterns += patterns('',
  (r'^accounts/logout/$', 'django.contrib.auth.views.logout',
    {'next_page' : '/'}),  # redirect to '/' instead of login page
  # django-registration
  (r'^accounts/', include('registration.backends.default.urls')),
  (r'^accounts/', include('django.contrib.auth.urls')),
)

# Browse the false mailbox, for demo websites:
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^dev/webmail/', include('webmail_locmem.urls')),
    )

# Enable the auto-admin:
from django.contrib import admin
import django
admin.autodiscover()

urlpatterns += patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^dev/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^dev/', include(admin.site.urls)),
)
# TODO: implement a lighter admin interface for non-dev admins (to
# manage project configurations, skills categories, etc.)
# It could reside at '^siteadmin/'.

# Static content
if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^' + settings.STATIC_MEDIA_URL[1:] + '(?P<path>.*)$', 'serve',
         {'document_root' : settings.STATIC_MEDIA_ROOT, 'show_indexes' : True}),
    )

savane/svpeople/models.py
# Jobs models
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
#
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
from django.contrib.auth import models as auth_models
from django.utils.translation import ugettext, ugettext_lazy as _
import datetime


class OpenJobManager(models.Manager):
    def get_query_set(self):
        return super(self.__class__, self).get_query_set().filter(status=1)
class Job(models.Model):
    status_CHOICES = (
        ('1', _('Open')),
        ('2', _('Filled')),
        ('3', _('Deleted')),
        )
    group = models.ForeignKey(auth_models.Group)
    created_by =  models.ForeignKey(auth_models.User)
    title = models.CharField(max_length=255, verbose_name=_("Short description"))
    description = models.TextField(_("Long description"))
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(_("Status"), max_length=1, choices=status_CHOICES)
    category = models.ForeignKey("Category", verbose_name=_("Category"))

    objects = models.Manager() # default manager
    open_objects = OpenJobManager()

    def __unicode__(self):
        return "%s" % (self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('savane:svpeople:job_detail', [self.id])

class Label(models.Model):
    class Meta:
        abstract = True
    active = models.BooleanField(default=True)
    label = models.CharField(max_length=255)

    def __unicode__(self):
        return "%s" % (self.label)

class Category(Label):
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")
    def open_job_set(self):
        return self.job_set.filter(status=1)

class Skill(Label):
    class Meta:
        verbose_name = _("skill")
        verbose_name_plural = _("skills")
        ordering = ('label',)
class SkillLevel(Label):
    class Meta:
        verbose_name = _("skill level")
        verbose_name_plural = _("skill levels")
class SkillYear(Label):
    class Meta:
        verbose_name = _("skill year")
        verbose_name_plural = _("skill years")

# Cf. fixtures/*.yaml
default_categories_marked_for_translation = (
    _("Developer"),
    _("Project manager"),
    _("Unix admin"),
    _("Doc writer"),
    _("Tester"),
    _("Support manager"),
    _("Graphic/other designer"),
    _("Translator"),
)
default_skill_levels_marked_for_translation = (
    _("Base knowledge"),
    _("Good knowledge"),
    _("Master"),
    _("Master apprentice"),
    _("Expert"),
)
default_skill_years_marked_for_translation = (
    _("(< 6 months)"),
    _("6 Mo - 2 yr"),
    _("2 yr - 5 yr"),
    _("5 yr - 10 yr"),
    _("> 10 years"),
)

class JobInventory(models.Model):
    class Meta:
        verbose_name = _("job inventory")
        verbose_name_plural = _("job inventories")
    job = models.ForeignKey(Job)
    skill = models.ForeignKey(Skill)
    skill_level = models.ForeignKey(SkillLevel)
    skill_year = models.ForeignKey(SkillYear)


from savane.utils.fields import AutoOneToOneField
class UserInfo(models.Model):
    user = AutoOneToOneField(auth_models.User, primary_key=True, related_name="svpeopleuserinfo")
    resume = models.TextField(_("Resume"))
    view_skills = models.BooleanField(_("Publicly viewable"), default=False)

class SkillInventory(models.Model):
    class Meta:
        verbose_name = _("skill inventory")
        verbose_name_plural = _("skill inventories")
    user = models.ForeignKey(auth_models.User)
    skill = models.ForeignKey(Skill)
    skill_level = models.ForeignKey(SkillLevel)
    skill_year = models.ForeignKey(SkillYear)

savane/svpeople/forms.py
# Forms for jobs
# Copyright (C) 2010  Sylvain Beucler
#
# This file is part of Savane.
# 
# Savane is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# Savane is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django import forms
import django.contrib.auth.models as auth_models
import models as svpeople_models
from django.utils.translation import ugettext
from django.utils.translation import ugettext as _

class JobForm(forms.ModelForm):
    class Meta:
        model = svpeople_models.Job
        fields = ('category', 'status', 'title', 'description', )
    description = forms.CharField(widget=forms.Textarea(attrs={'cols':'70','rows':'15'}))

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        # Translate categories from database
        self.fields['category'].choices = \
            [ (k,ugettext(v)) for k,v in self.fields['category'].choices ]

class DuplicateValidation(object):
    # Check that the same skill is not submitted twice
    def clean(self, *args, **kwargs):
        super(DuplicateValidation, self).clean(*args, **kwargs)
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        skills = []
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            if form.cleaned_data.get('DELETE', False):
                continue
            if not form.cleaned_data.get('skill', False):
                continue
            skill = form.cleaned_data['skill'].pk
            if skill in skills:
                raise forms.ValidationError, "Skill already in your inventory"
            skills.append(skill)

from django.forms.models import inlineformset_factory
GenericJobInventoryFormSet = inlineformset_factory(svpeople_models.Job, svpeople_models.JobInventory)
class JobInventoryFormSet(DuplicateValidation, GenericJobInventoryFormSet): pass

GenericSkillInventoryFormSet = inlineformset_factory(auth_models.User, svpeople_models.SkillInventory)
class SkillInventoryFormSet(DuplicateValidation, GenericSkillInventoryFormSet): pass

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = svpeople_models.UserInfo
        fields = ('view_skills', 'resume')
    resume = forms.CharField(widget=forms.Textarea(attrs={'cols':'70','rows':'15'}), label=_("Resume"))

templates/svpeople/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}{{title}}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

{% include "svpeople/index_custom.html" %}

<table class="box">
<tr><th>{% trans "Category" %}</th></tr>
{% for object in category_list %}
<tr class="{% cycle 'boxitemalt' 'boxitem' %}">
  <td><a href="{% url savane:svpeople:job_list_by_category object.pk %}"
    >{% trans object.label %}</a>
    ({{object.open_job_set.count}})
  </td>
</tr>
{% endfor %}
</table>

<table class="box">
<tr><th>{% trans "Project type" %}</th></tr>
{% for tuple in type_and_count %}
<tr class="{% cycle 'boxitemalt' 'boxitem' %}">
  <td><a href="{% url savane:svpeople:job_list_by_type tuple.type.pk %}"
    >{{tuple.type.name}}</a>
    ({{tuple.count}})
  </td>
</tr>
{% endfor %}
</table>

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/index_custom.html
{% load i18n %}
<p>{% trans "Browse through the category menu to find projects looking for your help." %}</p>
<p>{% blocktrans with '<em>' as begin_em and '</em>' as end_em %}If you're a project admin, log in, enter your project page, follow the project admin link (in the navigation bar) and you will find a {{begin_em}}Post Jobs{{end_em}} section where you can submit help wanted requests to appear in this list.{% endblocktrans %}</p>
<p>{% trans "To suggest new job categories, visit the support manager." %}</p>

templates/svpeople/job_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load svmarkup %}
{% load svmembership %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}{{title}}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

<h1>
  {% trans object.category.label %} {% trans "wanted for" %}
  <a href="{% url savane:svmain:group_detail object.group.name %}">{{object.group.svgroupinfo.full_name}}</a>
  {% if request.user|is_admin_of:object.group %}
  [<a href="{% url savane:svpeople:job_edit object.pk %}">{% trans "Edit" %}</a>]
  {% endif %}
</h1>

<p>
  <span class="preinput">{% trans "Submitted By:" %}</span>
  <a href="{% url savane:svmain:user_detail object.created_by.username %}"
    >{{object.created_by.username}}</a><br />
  <span class="preinput">{% trans "Date:" %}</span> {{object.date}}<br />
  <span class="preinput">{% trans "Status:" %}</span> {{object.get_status_display}}
</p>

<p>{{object.group.svgroupinfo.type.description}}</p>
{% firstof object.group.svgroupinfo.long_description|svmarkup_full object.group.svgroupinfo.short_description %}
<p>
  <span class="preinput">{% trans "License" %}</span>
  <a href="{% url savane:svmain:license_detail object.group.svgroupinfo.license.slug %}"
    >{{object.group.svgroupinfo.license.name}}</a>
  <br />
  <span class="preinput">{% trans "Development Status" %}</span>: {{object.group.svgroupinfo.devel_status}}</p>
<p>
  <span class="preinput">{% trans "Details (job description, contact ...):" %}</span>
  {{object.title}}
</p>

{{object.description|svmarkup_full}}

<h2>{% trans "Required Skills:" %}</h2>

{% with object.jobinventory_set.select_related as object_list %}
{% include "svpeople/job_inventory.inc" %}
{% endwith %}

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/job_form.html
{% extends "base.html" %}
{% load i18n %}
{% load svmarkup %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}{{title}}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

{% if not add %}
  {% if formset.non_form_errors %}
  <div class="warn">{{formset.non_form_errors}}</div>
  {% endif %}
{% endif %}

<p>
{% if add %}
{% trans "Start by filling in the fields below. When you click continue, you will be shown a list of skills and experience levels that this job requires." %}
{% else %}
{% trans "Now you can edit/change the list of skills attached to this posting." %}
{% trans "Developers will be able to match their skills with your requirements." %}
<br /><br />
{% trans "All postings are automatically closed after two weeks." %}
{% endif %}
</p>

<form action="" method="post">{% csrf_token %}

<table>
{{form.as_table}}
</table>

{% if not add %}
{% include "svpeople/skill_inventory_edit.inc" %}
{% endif %}

<input type="submit" value="{{action}}" />
</form>

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/job_list_by_category.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}
{% blocktrans with category.label as category_label %}Projects looking for {{category_label}}{% endblocktrans %}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

{% include "svpeople/job_list.inc" %}

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/job_list_by_group.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}{{title}}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

<p>{% trans "Here is a list of positions available for this project." %}</p>

{% include "svpeople/job_list.inc" %}

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/job_list_by_type.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% blocktrans %}People at {{site_name}}{% endblocktrans %}{% trans ": " %}{{title}}
{% endblock %}

{% block icon %}people{% endblock %}

{% block content %}

{% include "svpeople/job_list.inc" %}

{% endblock %}

{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}

templates/svpeople/userinfo_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "My account configuration" %}{% trans ": " %}{{title}}
{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}

<h2>{% trans "Resume - Description of experience" %}</h2>

<table>
{{form}}
</table>

<h2>{% trans "Skills" %}</h2>

{% if formset.non_form_errors %}
<div class="warn">{{formset.non_form_errors}}</div>
{% endif %}

{% include "svpeople/skill_inventory_edit.inc" %}

<input type="submit" value="{% trans "Update" %}" />
</form>

{% endblock %}
{% comment %}
Local Variables: **
mode: django-html **
tab-width: 4 **
indent-tabs-mode: nil **
End: **
{% endcomment %}